"""Generate src/head_mock_data.h from the HEAD mock CSV (IMU columns only).

The board plays this back over UDP on a BOOT short-press (see
components/peripherals/mock_playback.cpp). Only the 10 IMU fields that fit the
52-byte UDP packet are embedded; the CSV's EEG columns are dropped.

Runs two ways:
  - standalone:            python3 scripts/gen_head_mock.py
  - PlatformIO pre-script: extra_scripts = pre:scripts/gen_head_mock.py

Idempotent: the header embeds the source CSV's sha256 and is only rewritten
when the CSV changes. If the CSV is missing but a header exists, the existing
header is kept (so builds don't require the sibling rpi-receiver checkout).
Override the CSV location with the HEAD_MOCK_CSV env var.
"""
from __future__ import annotations

import csv
import hashlib
import os
import sys
from pathlib import Path

# Under PlatformIO this runs as an SCons pre-script: __file__ is undefined and
# the project root comes from the build environment instead.
try:
    Import("env")  # type: ignore[name-defined]  # noqa: F821
    PROJECT_DIR = Path(env["PROJECT_DIR"])  # type: ignore[name-defined]  # noqa: F821
except NameError:
    PROJECT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_CSV = (PROJECT_DIR.parent / "rpi-receiver" / "mock-csv"
               / "10_squats_clean_biometric_data_simulation" / "HEAD_Head_main.csv")
# Lives inside the peripherals component: mock_playback.cpp is its only consumer.
HEADER_PATH = PROJECT_DIR / "components" / "peripherals" / "head_mock_data.h"

IMU_FIELDS = ("ax_g", "ay_g", "az_g", "gx_dps", "gy_dps", "gz_dps",
              "hx_g", "hy_g", "hz_g", "imu_temp_c")

# The head node has no biometrics, so the mock borrows them from the chest (ECG:
# heart rate, respiration, HRV) and wrist (PPG: SpO2) reference files in the same
# exercise folder, merged by row. Resting defaults are used if they're missing.
BIO_SOURCES = (
    ("hr", "WA_Chest.csv", "ecg_hr_bpm", 92.0),
    ("spo2", "WD_L_Wrist.csv", "ppg_spo2_pct", 97.0),
    ("resp", "WA_Chest.csv", "resp_rate_bpm", 20.0),
    ("hrv", "WA_Chest.csv", "ecg_rmssd_ms", 44.0),
)


def sha_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def float_literal(v: float) -> str:
    s = f"{v:g}"
    if "." not in s and "e" not in s:
        s += ".0"  # "0f" is not a valid C literal; "0.0f" is
    return s + "f"


def existing_sha(header: Path) -> str | None:
    if not header.exists():
        return None
    for line in header.read_text().splitlines():
        if line.startswith("// source-sha256:"):
            return line.split(":", 1)[1].strip()
    return None


def _read_bio_column(csv_dir: Path, filename: str, column: str):
    path = csv_dir / filename
    if not path.exists():
        return None
    with path.open(newline="") as handle:
        return [float(row[column]) for row in csv.DictReader(handle)]


def generate(csv_path: Path, header: Path) -> None:
    rows = []
    t_values = []
    with csv_path.open(newline="") as handle:
        for row in csv.DictReader(handle):
            rows.append(tuple(float(row[f]) for f in IMU_FIELDS))
            t_values.append(float(row["t_s"]))
    if len(rows) < 2:
        raise SystemExit(f"{csv_path} has too few rows ({len(rows)})")
    cadence_ms = round((t_values[1] - t_values[0]) * 1000)

    # Merge biometrics from the sibling node files (defaults when absent).
    bio_cols = []
    for _key, filename, column, default in BIO_SOURCES:
        col = _read_bio_column(csv_path.parent, filename, column)
        bio_cols.append((col, default))

    lines = [
        "// Auto-generated by scripts/gen_head_mock.py — do not edit.",
        f"// source: {csv_path.name} + chest/wrist biometrics",
        f"// source-sha256: {sha_of(csv_path)}",
        "#pragma once",
        "",
        f"#define HEAD_MOCK_ROWS {len(rows)}",
        f"#define HEAD_MOCK_CADENCE_MS {cadence_ms}",
        "",
        "typedef struct {",
        "    float ax_g, ay_g, az_g;",
        "    float gx_dps, gy_dps, gz_dps;",
        "    float hx_g, hy_g, hz_g;",
        "    float imu_temp_c;",
        "    float hr, spo2, resp, hrv;  // mock biometrics (chest/wrist)",
        "} head_mock_row_t;",
        "",
        "static const head_mock_row_t HEAD_MOCK_DATA[HEAD_MOCK_ROWS] = {",
    ]
    for i, values in enumerate(rows):
        bio = tuple(col[i] if col and i < len(col) else default
                    for col, default in bio_cols)
        formatted = ", ".join(float_literal(v) for v in values + bio)
        lines.append(f"    {{{formatted}}},")
    lines.append("};")
    header.write_text("\n".join(lines) + "\n")
    print(f"gen_head_mock: wrote {header} "
          f"({len(rows)} rows @ {cadence_ms} ms, IMU + bio)")


def main() -> None:
    csv_path = Path(os.environ.get("HEAD_MOCK_CSV", DEFAULT_CSV))
    if not csv_path.exists():
        if HEADER_PATH.exists():
            print(f"gen_head_mock: {csv_path} not found — keeping existing "
                  f"{HEADER_PATH.name}", file=sys.stderr)
            return
        raise SystemExit(
            f"gen_head_mock: {csv_path} not found and no {HEADER_PATH} exists. "
            f"Check out rpi-receiver next to P1_Embedded_Software or set "
            f"HEAD_MOCK_CSV to a HEAD node CSV.")
    if existing_sha(HEADER_PATH) == sha_of(csv_path):
        return  # up to date; keep the build quiet
    generate(csv_path, HEADER_PATH)


main()
